server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri:  mongodb://root:123@localhost:27017
      database: xc_cms
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: xuecheng
      password: xuecheng
      virtualHost: /xuecheng
  freemarker:
    cache: false # 关闭缓存，方便测试
    settings:
      template_update_delay: 0
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: xuecheng
        password: xuecheng
        virtualHost: /xuecheng